### ISSUE TITLE
Bug: Unable to save, export the phenotypes - phema-authoring tool

### ISSUE THREAD

**Issue by trsree** [PheMA/phema-author#7]
Hi,

I downloaded your latest phema-author tool code from GitHub. I followed the ReadMe instructions, and installed the dependencies(node, npm, ruby, compass, bower) in my Windows7 laptop. I could bring up the application by giving grunt serve command, Logged In as a Test person. I could create all the phenotypes, but unable to save and export them. I am getting an error while saving it: There was an error trying to save your phenotype definition - but i cant find any errors in the command prompt logs. Please find the error attached. Please let me know how to resolve.. Thanks for all help.
![image](https://user-images.githubusercontent.com/5104605/27653153-3066f8e2-5c0c-11e7-9853-633479df46b5.png)

**Comment by lrasmus** [comment]
@trsree - sorry, I wasn't routinely monitoring this on the site and didn't get a notification of the issue!  Let me know if you're still having this problem.

**Comment by lrasmus** [comment]
Should be resolved now for PheKB integration as reported by @japacheco42 

@trsree - happy to revisit at any time if you're still having issues.
